### ISSUE TITLE
"//fast" not working.

### ISSUE THREAD

**Issue by Flexico** [Mumfrey/WorldEditWrapper#2]
I was told to use the //fast command to edit blocks without triggering block updates, but it doesn't seem to be working. Editing in water source blocks makes a mess as they spill all over.

**Comment by Mumfrey** [comment]
//fast can't be easily supported in vanilla minecraft because it doesn't have bukkit's advanced world-changing functionality which is used to achieve that behaviour when running on bukkit. I've been experimenting with ways to implement this but none are reliable enough to be released yet. When I discover a way to do this I will release a version with that feature but at the moment it can't be supported.

**Comment by Flexico** [comment]
Well then how did SinglePlayerCommands do it? Could you look at that for a method?

**Comment by Mumfrey** [comment]
SinglePlayerCommands used to override base classes, that is not a viable option any more which is exactly why SPC is not updated.

**Comment by q3hardcore** [comment]
Well, not exactly. I could have a look at adding //fast support :)

**Comment by Mumfrey** [comment]
As I mentioned above I will be implementing //fast, it's just not a priority because it's complex. Making it _work_ in a very basic manner is very simple, making it work as well as it does on Bukkit is quite difficult because Minecraft simply doesn't have some of Bukkit's mechanisms so they need to be simulated by the mod, the main issue is with things like snow, flower pots, and heads which it's very hard to stop other block updates interfering.

Again this is planned, but I don't really uphold that it's a bug report because it's a hacky behaviour of worldedit in the first place.
